### ISSUE TITLE
"Ready" button not functioning with Aetherium enabled with other mods

### ISSUE THREAD

**Issue by Avarice** [KomradeSpectre/AetheriumMod#70]
[LogOutput.log](https://github.com/KomradeSpectre/AetheriumMod/files/13984352/LogOutput.log)

Singleplayer game start button does not have function when Aetherium is enabled. Multiplayer ready button can be clicked to trigger the countdown, but on reaching zero, nothing happens.

**Comment by KomradeSpectre** [comment]
Assembly.GetTypes() seems to have broke in your pack. Are you using the latest versions of your mods? Mine only shows up first on the Assembly.GetTypes() because my mod's name is Aetherium, starting with an A. Also, you have a mod breaking Recalculate stats early on in the load too, which my mod, as well as countless others use.

**Comment by Avarice** [comment]
Yeah, using all of the most recent versions of everything. I don't think it's Aetherium breaking things, but it was the boot that I had disabled only that that allowed me to start a run. What else should I do to try to track down what's breaking it?

**Comment by KomradeSpectre** [comment]
Are you? You have a fair amount of duplicates in your pack, there is a patcher failing to load at the start, there is Rakshi failing erroring out at the start, there's warnings that you don't have the latest version of some things (R2API). I'm not sure this is central to my mod, because Aetherium only encounters an error maybe 9000 lines down after many other things have failed. Closing this.
